const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const terminal=$('#terminal'), runner=$('#runner');
let games=[];
const gameArtwork=new Map();
const selectedGames=new Set();
let commandRunning=false;

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
$('#closeRunner').onclick=()=>runner.classList.remove('open');
$('#cancelRunner').onclick=async()=>{if(!confirm('Stop the active operation? Partial downloads remain resumable.'))return;const result=await fetch('/api/cancel',{method:'POST'}).then(r=>r.json());notify(result.ok?'Operation stopped':'Could not stop operation',result.ok?'You can resume the download later.':'No cancellable operation was found.',!result.ok)};

function stripAnsi(value){return value.replace(/[\u001B\u009B][[\]()#;?]*(?:(?:(?:[a-zA-Z\d]*(?:;[-a-zA-Z\d\/#&.:=?%@~_]+)*)?\u0007)|(?:(?:\d{1,4}(?:;\d{0,4})*)?[\dA-PR-TZcf-nq-uy=><~]))/g,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n')}
async function run(command,{flags=[],options=[]}={}){
  if(commandRunning){notify('Command already running','Wait for the current operation to finish.',true);return false}
  commandRunning=true;
  runner.classList.add('open'); terminal.textContent=''; $('#runnerTitle').textContent=command.replaceAll('-',' ');
  let exitCode=null;
  const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,flags,options})});
  const reader=response.body.getReader(), decoder=new TextDecoder(); let buffer='';
  while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line)continue;const e=JSON.parse(line);if(e.data)terminal.textContent+=stripAnsi(e.data);if(e.message)terminal.textContent+='\n'+e.message;if(e.type==='error')exitCode=1;if(e.type==='exit'){exitCode=e.code;terminal.textContent+=`\n\nFinished with code ${e.code}.`}terminal.scrollTop=terminal.scrollHeight}}
  commandRunning=false;
  return exitCode===0;
}
function notify(title,message,error=false){$('#toastTitle').textContent=title;$('#toastMessage').textContent=message;$('#toast').classList.toggle('error',error);$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
const opt=(key,value)=>({key,value});
const formatSize=bytes=>bytes>=1099511627776?`${(bytes/1099511627776).toFixed(1)} TB`:`${(bytes/1073741824).toFixed(1)} GB`;
async function loadLibrary(){try{const data=await fetch('/api/library').then(r=>r.json());games=data.games;gameArtwork.clear();games.forEach(game=>gameArtwork.set(game.title,game.game_id));$('#statGames').textContent=games.length;$('#statBacked').textContent=games.filter(g=>g.backed_up).length;$('#statSize').textContent=formatSize(games.reduce((sum,g)=>sum+g.total_size,0));renderGames();runner.classList.remove('open')}catch(e){notify('Library failed to load',e.message,true)}}
$('#refreshBtn').onclick=async()=>{const ok=await run('update');if(ok){notify('Library synced','Your local game list is up to date.');await loadLibrary()}};
$('#listGames').onclick=loadLibrary;
function renderGames(){const q=$('#search').value.toLowerCase(),status=$('#statusFilter').value,platform=$('#platformFilter').value,sort=$('#sortGames').value;let filtered=games.filter(g=>g.title.toLowerCase().includes(q)&&(status==='all'||(status==='backed')===g.backed_up)&&(platform==='all'||g.platforms.includes(platform)));filtered.sort((a,b)=>sort==='size'?b.total_size-a.total_size:sort==='status'?Number(b.backed_up)-Number(a.backed_up):a.title.localeCompare(b.title));$('#games').innerHTML=filtered.length?filtered.map((g,i)=>`<article class="game${selectedGames.has(g.title)?' selected':''}" data-game="${encodeURIComponent(g.title)}"><img loading="lazy" src="/api/artwork?id=${g.game_id}" alt="" onerror="this.classList.add('missing')"><span class="game-shade"></span><span class="status-badge ${g.backed_up?'backed':'missing'}">${g.backed_up?'✓ '+t('BACKED UP'):t('NOT BACKED UP')}</span><button class="select-game" aria-label="Select ${escapeHtml(g.title)}">${selectedGames.has(g.title)?'✓':'+'}</button><button class="detail-game" data-id="${g.game_id}" aria-label="Details ${escapeHtml(g.title)}"><small>${g.file_count} files · ${formatSize(g.total_size)}</small><strong>${escapeHtml(g.title)}</strong></button></article>`).join(''):'<div class="empty"><h3>No matching games</h3><p>Try changing the filters.</p></div>';$$('.select-game').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const name=decodeURIComponent(btn.closest('.game').dataset.game);selectedGames.has(name)?selectedGames.delete(name):selectedGames.add(name);renderGames();updateSelection()});$$('.detail-game').forEach(btn=>btn.onclick=()=>openGameDetail(btn.dataset.id))}
async function openGameDetail(id){const modal=$('#gameDetail'),content=$('#detailContent');content.innerHTML='<p>Loading game details…</p>';modal.showModal();try{const data=await fetch(`/api/game?id=${id}`).then(r=>{if(!r.ok)throw new Error('Game details unavailable');return r.json()});const platforms=[...new Set(data.downloads.map(x=>x.platform))].join(', ');content.innerHTML=`<img class="detail-art" src="/api/artwork?id=${id}" alt=""><p class="eyebrow">${t('GAME DETAILS')}</p><h2>${escapeHtml(data.game.title)}</h2><div class="detail-meta"><span>${data.downloads.length} files</span><span>${formatSize(data.downloads.reduce((s,x)=>s+Number(x.size),0))}</span><span>${escapeHtml(platforms||'—')}</span><span>${data.extras.length} extras</span></div><h3>Installers & patches</h3><div class="file-list">${data.downloads.slice(0,30).map(x=>`<div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.platform)} · ${escapeHtml(x.language)} · ${formatSize(Number(x.size))}${Number(x.is_patch)?' · patch':''}</small></div>`).join('')}</div>${data.extras.length?`<h3>Extras</h3><div class="file-list">${data.extras.map(x=>`<div><b>${escapeHtml(x.name)}</b><small>${formatSize(Number(x.size))}</small></div>`).join('')}</div>`:''}`}catch(e){content.innerHTML=`<h2>Details unavailable</h2><p>${escapeHtml(e.message)}</p>`}}
$('#closeDetail').onclick=()=>$('#gameDetail').close();
function updateSelection(){const count=selectedGames.size;$('#selectionCount').textContent=count;$('#selectionBar').classList.toggle('show',count>0);$('#selectedSummary').classList.toggle('active',count>0);$('#selectedSummary').textContent=count?`${count} ${t('games selected')}: ${[...selectedGames].join(', ')}`:t('No library selection — all matching games will be downloaded.')}
$('#clearSelection').onclick=()=>{selectedGames.clear();renderGames();updateSelection()};
$('#backupSelection').onclick=()=>{showView('download');updateSelection()};
$('#search').oninput=renderGames;$('#statusFilter').onchange=renderGames;$('#platformFilter').onchange=renderGames;$('#sortGames').onchange=renderGames;
$('#downloadBtn').onclick=async()=>{const destination=$('#directory').value.trim()||$('#destinationHint strong').textContent;notify('Backup started',`Files will be saved under ${destination}`);await run('download',{flags:[...($('#extras').checked?['extras']:[]),...($('#fallback').checked?['language-fallback-english']:[]),...($('#updateFirst').checked?['update']:[])],options:[opt('directory',$('#directory').value),opt('os',$('#os').value),opt('language',$('#language').value),...[...selectedGames].map(name=>opt('only',name)),opt('only',$('#only').value)]})};
$('#savesBtn').onclick=()=>run('download-saves',{options:[opt('directory',$('#saveDirectory').value)]});
$('#verifyBtn').onclick=()=>run('download',{flags:['remove-invalid',...($('#repairExtras').checked?['extras']:[])],options:[...[...selectedGames].map(name=>opt('only',name))]});
const theme=$('#theme');theme.value=localStorage.getItem('gog-vault-theme')||'vault';document.documentElement.dataset.theme=theme.value;theme.onchange=()=>{document.documentElement.dataset.theme=theme.value;localStorage.setItem('gog-vault-theme',theme.value)};
$('#loginBtn').onclick=async()=>{const code=$('#loginCode').value.trim();if(!code){notify('Missing login code','Paste the GOG redirect URL first.',true);return}$('#loginCode').value='';$('#loginBtn').disabled=true;$('#loginBtn').textContent='Connecting…';try{const ok=await run('code-login',{options:[opt('code',code)]});notify(ok?'Account connected':'Connection failed',ok?'Your GOG session is ready. You can sync the library now.':'Open the activity panel for details.',!ok);$('#loginBtn').textContent=ok?'✓ Account connected':'Connect account'}catch(e){notify('Connection failed',e.message,true);$('#loginBtn').textContent='Connect account'}finally{$('#loginBtn').disabled=false}};
async function refreshStatus(){try{const s=await fetch('/api/status').then(r=>r.json());$('#statusDot').classList.toggle('ok',s.appReady);$('#systemText').textContent=s.activeJob?`${s.activeJob.command} running in background`:(s.appReady?`Engine ready · PHP ${s.php}`:'Run composer install');const target=$('#destinationHint strong');if(target)target.textContent=s.downloadLabel||s.downloadDirectory;return s}catch{$('#systemText').textContent='Engine unavailable';return null}}
async function initializeLibrary(){const status=await refreshStatus();if(!status)return;if(!status.activeJob){await loadLibrary();return}const previous=await fetch('/api/log').then(r=>r.json());terminal.textContent=previous.log||'';$('#runnerTitle').textContent=status.activeJob.command;runner.classList.add('open');notify('Background task active',`${status.activeJob.command} is still running. Its activity log has been restored.`);const poll=setInterval(async()=>{const next=await refreshStatus();if(next?.activeJob){const log=await fetch('/api/log').then(r=>r.json());terminal.textContent=log.log||terminal.textContent;terminal.scrollTop=terminal.scrollHeight}else if(next){clearInterval(poll);notify('Operation finished','Loading your updated library.');await loadLibrary()}},2000)}
initializeLibrary();
window.addEventListener('beforeunload',e=>{if(commandRunning){e.preventDefault();e.returnValue=''}});
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
