const translations={tr:{
  'Library':'Kütüphane','Download':'Yedekle','Cloud saves':'Bulut kayıtları','Account':'Hesap',
  'LOCAL COLLECTION':'YEREL KOLEKSİYON','Your games, safely archived.':'Oyunların, güvenle arşivlendi.',
  '↻ Sync library':'↻ Kütüphaneyi güncelle','QUICK START':'HIZLI BAŞLANGI','Bring your GOG library home.':'GOG kütüphaneni kendi arşivine al.',
  'Sync your owned games, then create verified offline backups with resumable downloads.':'Oyunlarını eşitle, doğrulanan ve devam ettirilebilen çevrimdışı yedekler oluştur.',
  'Create a backup →':'Yedek oluştur →','Load games':'Oyunları yükle','Library not loaded yet':'Kütüphane henüz yüklenmedi',
  'Sign in, sync metadata, then load your games.':'Giriş yap, verileri eşitle ve oyunlarını yükle.',
  'BACKUP BUILDER':'YEDEK OLUŞTURUCU','Choose what to archive':'Arşivlenecek içerikleri seç','Destination':'Hedef klasör','Platform':'Platform','Language':'Dil',
  'Additional exact game title':'Ek oyun adı','Include extras':'Ekstraları dahil et','Fall back to English':'İngilizceye geri dön','Sync before download':'İndirmeden önce eşitle',
  'Start verified download ↓':'Doğrulanmış indirmeyi başlat ↓','CLOUD SAVES':'BULUT KAYITLARI','Back up your progress':'İlerlemeni yedekle',
  'Download cloud saves for every supported game into your archive.':'Desteklenen oyunların bulut kayıtlarını arşivine indir.','Back up saves':'Kayıtları yedekle',
  'Connect securely with a login code':'Giriş koduyla güvenli bağlan','Open the GOG authorization page.':'GOG yetkilendirme sayfasını aç.',
  'Sign in and copy the final blank-page URL.':'Giriş yap ve son boş sayfanın adresini kopyala.','Paste it below; it is sent only to this local app.':'Aşağıya yapıştır; yalnızca bu yerel uygulamaya gönderilir.',
  'Open GOG sign-in ↗':'GOG girişini aç ↗','Redirect URL or code':'Yönlendirme adresi veya kod','Connect account':'Hesabı bağla',
  'No library selection — all matching games will be downloaded.':'Kütüphaneden seçim yok — eşleşen tüm oyunlar indirilecek.','games selected':'oyun seçildi','SELECTED':'SEÇİLDİ','GOG LIBRARY':'GOG KÜTÜPHANESİ','Clear':'Temizle','Back up selected →':'Seçilenleri yedekle →',
  'Integrity':'Bütünlük','Settings':'Ayarlar','Games':'Oyun','Backed up':'Yedeklendi','Library size':'Kütüphane boyutu','All statuses':'Tüm durumlar','Not backed up':'Yedeklenmedi','All platforms':'Tüm platformlar','Title A–Z':'Ada göre A–Z','Largest first':'Önce en büyük','Backup status':'Yedek durumu','BACKED UP':'YEDEKLENDİ','NOT BACKED UP':'YEDEKLENMEDİ','GAME DETAILS':'OYUN AYRINTILARI','INTEGRITY & REPAIR':'BÜTÜNLÜK VE ONARIM','Verify your local archive':'Yerel arşivini doğrula','Verify & repair archive':'Arşivi doğrula ve onar','APPEARANCE':'GÖRÜNÜM','Make GOG Vault yours':'GOG Vault görünümünü özelleştir','Theme':'Tema',
  'Loading game details…':'Oyun ayrıntıları yükleniyor…','Game details unavailable':'Oyun ayrıntıları kullanılamıyor','Details unavailable':'Ayrıntılar kullanılamıyor','files':'dosya','extras':'ekstra','Installers & patches':'Kurulum dosyaları ve yamalar','Extras':'Ekstralar','patch':'yama',
  'Checks existing installers against GOG checksums. Missing or damaged files are downloaded again; valid files are skipped.':'Mevcut kurulum dosyalarını GOG sağlama toplamlarıyla denetler. Eksik veya bozuk dosyalar yeniden indirilir; geçerli dosyalar atlanır.','Select games in the Library, or verify the whole archive.':'Kütüphaneden oyun seç veya tüm arşivi doğrula.',
  'Overview':'Genel Bakış','Activity':'Aktivite','Storage':'Depolama','Sync & back up':'Eşitle ve yedekle','ARCHIVE HEALTH':'ARŞİV SAĞLIĞI','Waiting for library':'Kütüphane bekleniyor','Sync your library to calculate coverage.':'Kapsamı hesaplamak için kütüphaneni eşitle.','RECENT ACTIVITY':'SON İŞLEMLER','No activity yet.':'Henüz işlem yok.','Open activity':'Aktiviteyi aç','Your games':'Oyunların','Grouped view':'Gruplu görünüm','Updates':'Güncellemeler','Selected':'Seçili','DOWNLOAD MANAGER':'İNDİRME YÖNETİCİSİ','Activity & history':'Aktivite ve geçmiş','Refresh':'Yenile','No active operation.':'Etkin işlem yok.','History':'Geçmiş','STORAGE INSIGHTS':'DEPOLAMA ANALİZİ','Your local archive':'Yerel arşivin','Archived size':'Arşivlenen boyut','Expected size':'Beklenen boyut','Archived files':'Arşivlenen dosya','Archive location':'Arşiv konumu','No storage data yet.':'Henüz depolama verisi yok.','Custom background':'Özel arka plan','Background dim':'Arka plan karartma','Clear background':'Arka planı temizle','archived':'arşivlendi','games are backed up':'oyun yedeklendi','games need a backup. Sync and continue?':'oyunun yedeklenmesi gerekiyor. Eşitlenip devam edilsin mi?','Completed':'Tamamlandı','Failed':'Başarısız','ACTIVE NOW':'ŞİMDİ ETKİN','Stop':'Durdur','Activity unavailable':'Aktivite kullanılamıyor','of the expected archive size is present on disk.':'beklenen arşiv boyutunun diskte mevcut.','Storage scan failed':'Depolama taraması başarısız','Back up':'Yedekle','Verify & repair':'Doğrula ve onar','Re-download':'Yeniden indir','Download a fresh verified copy?':'Yeni ve doğrulanmış bir kopya indirilsin mi?','Image too large':'Görsel çok büyük','Choose an image smaller than 3 MB.':'3 MB’tan küçük bir görsel seç.','Restore from archive':'Arşivden geri yükle','Export':'Dışarı aktar'
}};
window.t=text=>(translations[localStorage.getItem('gog-vault-locale')||'en']||{})[text]||text;
const originalText=new WeakMap();
function applyLocale(locale){document.documentElement.lang=locale;localStorage.setItem('gog-vault-locale',locale);const dict=translations[locale]||{};document.querySelectorAll('button,h1,h2,h3,p,li,label,.eyebrow,.selected-summary,.checks span,.nav-label,.action-label').forEach(el=>{if(el.children.length&&el.tagName!=='BUTTON')return;if(!originalText.has(el))originalText.set(el,el.textContent.trim());const source=originalText.get(el);if(dict[source])el.textContent=dict[source];else if(locale==='en')el.textContent=source});const placeholders=locale==='tr'?{search:'Yerel kütüphanede ara…',directory:'Boş bırakırsan varsayılan klasör kullanılır',language:'tr',only:'İsteğe bağlı — seçili oyunlar zaten dahil',saveDirectory:'Kayıt yedekleme klasörü',loginCode:'GOG yönlendirme adresini yapıştır…'}:{search:'Search local library…',directory:'Leave empty to use the default',language:'en',only:'Optional — selected library games are already included',saveDirectory:'Cloud save backup folder',loginCode:'Paste the GOG redirect URL…'};Object.entries(placeholders).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.placeholder=value})}
const localeSelect=document.getElementById('locale');localeSelect.value=localStorage.getItem('gog-vault-locale')||((navigator.language||'').startsWith('tr')?'tr':'en');localeSelect.addEventListener('change',()=>applyLocale(localeSelect.value));applyLocale(localeSelect.value);
function applyExtendedLocale(){const dict=translations[localeSelect.value]||{};document.querySelectorAll('.stats span,option').forEach(el=>{const source=el.dataset.source||el.textContent.trim();el.dataset.source=source;el.textContent=dict[source]||source})}localeSelect.addEventListener('change',applyExtendedLocale);applyExtendedLocale();
